### ISSUE TITLE
Issue While connecting Frontend

### ISSUE THREAD

**Issue by Ajitchy** [AlmostEfficient/full-stack-solana-dev#1]
# Issue Description

I followed all the steps mentioned in the documentation and watched your YouTube video to create a "FullStack Solana development with React and Anchor" project. Everything worked smoothly until I reached the frontend part.

## Problem 1: IDL File

In the documentation, it instructs to create a new folder named `anchor` in `front-end/src` and copy over `target/types/counter.ts` (from the Anchor program) to a new file called `idl.ts`. The purpose of this step is to use the IDL to create TypeScript objects for interacting with the program.

However, when I opened `target/types/counter.ts`, I found that it's different from what was expected. It contains additional content, and the line `export const IDL: Counter = { ... }` is missing.
My `counter.ts` was like:

```markdown

```typescript
/**
 * Program IDL in camelCase format in order to be used in JS/TS.
 *
 * Note that this is only a type helper and is not the actual IDL. The original
 * IDL can be found at `target/idl/counter.json`.
 */
export type Counter = {
    "address": "2FcNSYHzEP7gXYZA4YMfiznRVAj7JpZF8Z4fWL7xw9jK",
    "metadata": {
        "name": "counter",
        "version": "0.1.0",
        "spec": "0.1.0",
        "description": "Created with Anchor"
    },
    "instructions": [
        {
            "name": "increment",
            "discriminator": [
                11,
                18,
                104,
                9,
                104,
                174,
                59,
                33
            ],
            "accounts": [
                {
                    "name": "counter",
                    "writable": true,
                    "pda": {
                        "seeds": [
                            {
                                "kind": "const",
                                "value": [
                                    99,
                                    111,
                                    117,
                                    110,
                                    116,
                                    101,
                                    114
                                ]
                            }
                        ]
                    }
                }
            ],
            "args": []
        },
        {
            "name": "initialize",
            "discriminator": [
                175,
                175,
                109,
                31,
                13,
                152,
                155,
                237
            ],
            "accounts": [
                {
                    "name": "user",
                    "writable": true,
                    "signer": true
                },
                {
                    "name": "counter",
                    "writable": true,
                    "pda": {
                        "seeds": [
                            {
                                "kind": "const",
                                "value": [
                                    99,
                                    111,
                                    117,
                                    110,
                                    116,
                                    101,
                                    114
                                ]
                            }
                        ]
                    }
                },
                {
                    "name": "systemProgram",
                    "address": "11111111111111111111111111111111"
                }
            ],
            "args": []
        }
    ],
    "accounts": [
        {
            "name": "counter",
            "discriminator": [
                255,
                176,
                4,
                245,
                188,
                253,
                124,
                25
            ]
        }
    ],
    "types": [
        {
            "name": "counter",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "count",
                        "type": "u64"
                    },
                    {
                        "name": "bump",
                        "type": "u8"
                    }
                ]
            }
        }
    ]
};

```

### Problem 2: Error in setup.js

After adding the `setup.js` file, which looks like this:

```javascript
import { IdlAccounts, Program } from "@coral-xyz/anchor";
import { IDL, Counter } from "./idl";
import { clusterApiUrl, Connection, PublicKey } from "@solana/web3.js";

const programId = new PublicKey("2FcNSYHzEP7gXYZA4YMfiznRVAj7JpZF8Z4fWL7xw9jK");
const connection = new Connection(clusterApiUrl("devnet"), "confirmed");

export const program = new Program<Counter>(IDL, programId, {
  connection,
});

export const [mintPDA] = PublicKey.findProgramAddressSync(
  [Buffer.from("mint")],
  program.programId,
);

export const [counterPDA] = PublicKey.findProgramAddressSync(
  [Buffer.from("counter")],
  program.programId,
);

export type CounterData = IdlAccounts<Counter>["counter"];
```

I encountered an error at the line `export const program = new Program<Counter>(IDL, programId, { connection, });`, which says:

```
Argument of type 'PublicKey' is not assignable to parameter of type 'Provider'.
Property 'connection' is missing in type 'PublicKey' but required in type 'Provider'.
```

### Problem 3: Error in Frontend

Following the subsequent steps and adding `<CounterState/>` in `App.tsx`, I encountered an error in the frontend console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'size')
    at new AccountClient (@coral-xyz_anchor.js?v=7e705056:10404:39)
    at @coral-xyz_anchor.js?v=7e705056:10369:30
    at Array.reduce (<anonymous>)
    at AccountFactory.build (@coral-xyz_anchor.js?v=7e705056:10368:70)
    at NamespaceFactory.build (@coral-xyz_anchor.js?v=7e705056:11480:51)
    at new _Program (@coral-xyz_anchor.js?v=7e705056:11560:98)
    at setup.ts:10:24
```

## Steps Taken
- Followed all steps mentioned in the documentation and video.
- Checked for typos and ensured correct file placements.
- Reviewed code for any missing or incorrect configurations.

## Additional Information
- Operating System: Windows(using WSL)
- solana --version; node -v; yarn --version; anchor --version
solana-cli 1.18.9 (src:9a7dd9ca; feat:3469865029, client:SolanaLabs)
v20.8.0
1.22.22
anchor-cli 0.30.0
```

**Comment by lostintime101** [comment]
Your first issue may be due to a breaking change in Anchor IDLs. Read more [here](https://github.com/coral-xyz/anchor/pull/2824). I was able to fix a similar issue by ensuring the version of Anchor in anchor.toml on the backend matched that in package.json for the frontend.

**Comment by adlonymous** [comment]
Same issue here, I tried switching back to Anchor 0.29.0 and that brought up different issues since the generated IDL was different

**Comment by CryptoCooker** [comment]
Same issue here.
https://github.com/coral-xyz/anchor/issues/2914#issuecomment-2084711323

**Comment by AlmostEfficient** [comment]
All your problems are related to using Anchor 0.30, which had a bunch of breaking changes. I suggest completing the project with 0.29 instead. 

Use `avm use 0.29` and `yarn add @coral-xyz/anchor@0.29`. Make sure Anchor is on v0.29 in your CLI, counter, AND front-end. You'll have to start over with the contract but you can reuse the front-end.

> Problem 1: IDL File
0.30 separates the types and the IDL. Instead of just making a types file, you'd copy over:

1. `/target/idl/counter.json`
2. `/target/types/counter.ts`

Put these in front-end/src/anchor and use them like this:
```ts
import * as idl from "./counter.json";
import type { Counter } from "./counter";
```

> Problem 2: Error in setup.js
When creating a program interface in Anchor 0.30, you [can't add `programId` anymore](https://github.com/coral-xyz/anchor/blob/master/CHANGELOG.md#:~:text=ts%3A%20Remove%20programId%20parameter%20of%20the%20Program%20constructor)

You'd just do sth like
```ts
export const program = new Program(idl, provider);
```

But I haven't gotten this to work yet cuz provider is breaking.

> Problem 3: Error in Frontend
Likely related to the IDL changes in v0.30 but I can't confirm.

**Comment by AlmostEfficient** [comment]
> Same issue here, I tried switching back to Anchor 0.29.0 and that brought up different issues since the generated IDL was different

@adlonymous see above. You need to have 0.29 in all three places.

**Comment by ilyacherevkov** [comment]
Pretty sure, I'm using 0.29.0, but I get in the browser console:

```
setup.ts:15 Uncaught ReferenceError: Buffer is not defined
    at setup.ts:15:4
```

**Comment by ilyacherevkov** [comment]
Added this into setup.ts and it appears to work now:

```
import { Buffer } from "buffer"
import * as process from "process"

globalThis.Buffer = Buffer as unknown as BufferConstructor;
globalThis.process = process as unknown as NodeJS.Process;
```

**Comment by gameuser1982** [comment]
> You'd just do sth like
> 
> ```ts
> export const program = new Program(idl, provider);
> ```
> 
> But I haven't gotten this to work yet cuz provider is breaking.
> 
> > Problem 3: Error in Frontend
> 
> Likely related to the IDL changes in v0.30 but I can't confirm.

Change Provider To AnchorProvider to fix Provider breaking:

https://coral-xyz.github.io/anchor/ts/classes/AnchorProvider.html

 Let me know if that fixes it for you cause I'm still working on figuring out the idl and typescript changes in Anchor 0.30.0. Why do they do stuff like rename functions and classes and make breaking idl changes? I hate it. I've been trying to get my frontend to work for 3 weeks now, meanwhile the on chain Rust code has been really smooth for me when it comes to cross compiling and deploying into bytecode.

**Comment by pwh-pwh** [comment]
How to build a Provider using only the public key?
