### ISSUE TITLE
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0

### ISSUE THREAD

**Issue by gameuser1982** [AlmostEfficient/full-stack-solana-dev#5]
So if I build and the deploy on the devnet and then use `anchor test --skip-build --skip-deploy` since I already built and deployed everything is find the first time around and the two tests pass. However second time around, I get an error during the simulation phase though the 2 tests pass:

```
candid@DESKTOP-5D7VSM9:~/counter$ anchor test --skip-build --skip-deploy

Found a 'test' script in the Anchor.toml. Running it as a test suite!

Running test suite: "/home/candid/counter/Anchor.toml"

yarn run v1.22.22
warning package.json: No license field
$ /home/candid/counter/node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'


  counter
SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    at Connection.sendEncodedTransaction (/home/candid/counter/node_modules/@solana/web3.js/src/connection.ts:5923:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Connection.sendRawTransaction (/home/candid/counter/node_modules/@solana/web3.js/src/connection.ts:5880:20)
    at sendAndConfirmRawTransaction (/home/candid/counter/node_modules/@coral-xyz/anchor/src/provider.ts:370:21)
    at AnchorProvider.sendAndConfirm (/home/candid/counter/node_modules/@coral-xyz/anchor/src/provider.ts:160:14)
    at MethodsBuilder.rpc [as _rpcFn] (/home/candid/counter/node_modules/@coral-xyz/anchor/src/program/namespace/rpc.ts:29:16) {
  logs: [
    'Program 6emLDu2jat6pho23Xcy3L2nnkAGu62YEuqpdvpJytSb7 invoke [1]',
    'Program log: Instruction: Initialize',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Allocate: account Address { address: DZR7F2P3S1zBSKYUHEfp44SzZ53pPaPsnvJxpermkBcN, base: None } already in use',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x0',
    'Program 6emLDu2jat6pho23Xcy3L2nnkAGu62YEuqpdvpJytSb7 consumed 6560 of 200000 compute units',
    'Program 6emLDu2jat6pho23Xcy3L2nnkAGu62YEuqpdvpJytSb7 failed: custom program error: 0x0'
  ],
  programErrorStack: ProgramErrorStack {
    stack: [
      [PublicKey [PublicKey(6emLDu2jat6pho23Xcy3L2nnkAGu62YEuqpdvpJytSb7)]],
      [PublicKey [PublicKey(11111111111111111111111111111111)]]
    ]
  }
}
    ✔ Is initialized! (495ms)
Transaction Signature: 4DVEfi5Gfbg4gvX1Yjr4ecorXE52m8UfsVq7yn1BiuYALmmXFFEEmdXTUEArUTviRubGpCgUh6fvAGmdEMvPWF3G
Count: 6
    ✔ Increment (482ms)


  2 passing (981ms)

Done in 2.64s.
```

Should I worry about this? It looks like it's happening because I am attempting to initialize an already initialized account. Since a constant seed is being used, the same address is being used on each test. How do I reset this without having to redeploy the contract on devnet? Or is that not possible?

Would it have any negative effect to the enduser that is interacting with the smart contract through the frontend? The frontend I setup does appear to work fine on devnet though I haven't tested in production on mainnet yet.

**Comment by AlmostEfficient** [comment]
You've two options here:

1. Use another seed - you'll abandon the old PDA. No biggie. 
2. Skip the init test - there's no reason to re-initialize lol. The PDA already exists. Try to read or write to it.
